// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnchorLink: typeof import('./src/components/anchor-link/index.vue')['default']
    BatchUpload: typeof import('./src/components/batch-upload/index.vue')['default']
    BulkOperations: typeof import('./src/components/bulk-operations/index.vue')['default']
    CascadePanel: typeof import('./src/components/cascade-panel/index.vue')['default']
    CascaderThree: typeof import('./src/components/cascader-three/index.vue')['default']
    CascaderTree: typeof import('./src/components/cascader-tree/index.vue')['default']
    ChangeReason: typeof import('./src/components/changeReason/changeReason.vue')['default']
    EditName: typeof import('./src/components/edit-name/index.vue')['default']
    Header: typeof import('./src/components/table/src/header/index.vue')['default']
    ImportExeclEcho: typeof import('./src/components/import-execl-echo/importExeclEcho.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutConventional: typeof import('./src/components/layout/src/layout-conventional.vue')['default']
    LayoutFullScreen: typeof import('./src/components/layout/src/layout-full-screen.vue')['default']
    LayoutSandwich: typeof import('./src/components/layout/src/layout-sandwich.vue')['default']
    LayoutTeambition: typeof import('./src/components/layout/src/layout-teambition.vue')['default']
    LayoutTop: typeof import('./src/components/layout/src/layout-top.vue')['default']
    MessageApi: typeof import('./src/components/message-api/index.vue')['default']
    NotificationApi: typeof import('./src/components/notification-api/index.vue')['default']
    Setting: typeof import('./src/components/setting/setting.vue')['default']
    Table: typeof import('./src/components/table/index.vue')['default']
    TakeInfo: typeof import('./src/components/take-info/index.vue')['default']
    Td: typeof import('./src/components/table/src/header/td.vue')['default']
    ToolTip: typeof import('./src/components/toolTip/index.vue')['default']
    UploadFile: typeof import('./src/components/upload-file/index.vue')['default']
    Wangeditor: typeof import('./src/components/wangeditor/wangeditor.vue')['default']
  }
}

export { }
