export const cityList: any = [
  {
    id: 1100,
    parent_id: null,
    region_code: '1100',
    name: '北京市',
    children: null,
  },
  {
    id: 1200,
    parent_id: null,
    region_code: '1200',
    name: '天津市',
    children: null,
  },
  {
    id: 1300,
    parent_id: null,
    region_code: '1300',
    name: '河北省',
    children: [
      {
        id: 169,
        parent_id: '1300',
        region_code: '1301',
        name: '石家庄市',
        children: null,
      },
      {
        id: 171,
        parent_id: '1300',
        region_code: '1302',
        name: '唐山市',
        children: null,
      },
      {
        id: 176,
        parent_id: '1300',
        region_code: '1303',
        name: '秦皇岛市',
        children: null,
      },
      {
        id: 173,
        parent_id: '1300',
        region_code: '1304',
        name: '邯郸市',
        children: null,
      },
      {
        id: 175,
        parent_id: '1300',
        region_code: '1305',
        name: '邢台市',
        children: null,
      },
      {
        id: 170,
        parent_id: '1300',
        region_code: '1306',
        name: '保定市',
        children: null,
      },
      {
        id: 178,
        parent_id: '1300',
        region_code: '1307',
        name: '张家口市',
        children: null,
      },
      {
        id: 179,
        parent_id: '1300',
        region_code: '1308',
        name: '承德市',
        children: null,
      },
      {
        id: 174,
        parent_id: '1300',
        region_code: '1309',
        name: '沧州市',
        children: null,
      },
      {
        id: 172,
        parent_id: '1300',
        region_code: '1310',
        name: '廊坊市',
        children: null,
      },
      {
        id: 177,
        parent_id: '1300',
        region_code: '1311',
        name: '衡水市',
        children: null,
      },
    ],
  },
  {
    id: 1400,
    parent_id: null,
    region_code: '1400',
    name: '山西省',
    children: [
      {
        id: 263,
        parent_id: '1400',
        region_code: '1401',
        name: '太原市',
        children: null,
      },
      {
        id: 264,
        parent_id: '1400',
        region_code: '1402',
        name: '大同市',
        children: null,
      },
      {
        id: 272,
        parent_id: '1400',
        region_code: '1403',
        name: '阳泉市',
        children: null,
      },
      {
        id: 269,
        parent_id: '1400',
        region_code: '1404',
        name: '长治市',
        children: null,
      },
      {
        id: 267,
        parent_id: '1400',
        region_code: '1405',
        name: '晋城市',
        children: null,
      },
      {
        id: 273,
        parent_id: '1400',
        region_code: '1406',
        name: '朔州市',
        children: null,
      },
      {
        id: 271,
        parent_id: '1400',
        region_code: '1407',
        name: '晋中市',
        children: null,
      },
      {
        id: 266,
        parent_id: '1400',
        region_code: '1408',
        name: '运城市',
        children: null,
      },
      {
        id: 268,
        parent_id: '1400',
        region_code: '1409',
        name: '忻州市',
        children: null,
      },
      {
        id: 270,
        parent_id: '1400',
        region_code: '1410',
        name: '临汾市',
        children: null,
      },
      {
        id: 265,
        parent_id: '1400',
        region_code: '1411',
        name: '吕梁市',
        children: null,
      },
    ],
  },
  {
    id: 1500,
    parent_id: null,
    region_code: '1500',
    name: '内蒙古自治区',
    children: [
      {
        id: 343,
        parent_id: '1500',
        region_code: '1501',
        name: '呼和浩特市',
        children: null,
      },
      {
        id: 344,
        parent_id: '1500',
        region_code: '1502',
        name: '包头市',
        children: null,
      },
      {
        id: 353,
        parent_id: '1500',
        region_code: '1503',
        name: '乌海市',
        children: null,
      },
      {
        id: 345,
        parent_id: '1500',
        region_code: '1504',
        name: '赤峰市',
        children: null,
      },
      {
        id: 347,
        parent_id: '1500',
        region_code: '1505',
        name: '通辽市',
        children: null,
      },
      {
        id: 348,
        parent_id: '1500',
        region_code: '1506',
        name: '鄂尔多斯市',
        children: null,
      },
      {
        id: 346,
        parent_id: '1500',
        region_code: '1507',
        name: '呼伦贝尔市',
        children: null,
      },
      {
        id: 349,
        parent_id: '1500',
        region_code: '1508',
        name: '巴彦淖尔市',
        children: null,
      },
      {
        id: 350,
        parent_id: '1500',
        region_code: '1509',
        name: '乌兰察布市',
        children: null,
      },
      {
        id: 352,
        parent_id: '1500',
        region_code: '1522',
        name: '兴安盟',
        children: null,
      },
      {
        id: 351,
        parent_id: '1500',
        region_code: '1525',
        name: '锡林郭勒盟',
        children: null,
      },
      {
        id: 354,
        parent_id: '1500',
        region_code: '1529',
        name: '阿拉善盟',
        children: null,
      },
    ],
  },
  {
    id: 2100,
    parent_id: null,
    region_code: '2100',
    name: '辽宁省',
    children: [
      {
        id: 132,
        parent_id: '2100',
        region_code: '2101',
        name: '沈阳市',
        children: null,
      },
      {
        id: 133,
        parent_id: '2100',
        region_code: '2102',
        name: '大连市',
        children: null,
      },
      {
        id: 134,
        parent_id: '2100',
        region_code: '2103',
        name: '鞍山市',
        children: null,
      },
      {
        id: 141,
        parent_id: '2100',
        region_code: '2104',
        name: '抚顺市',
        children: null,
      },
      {
        id: 145,
        parent_id: '2100',
        region_code: '2105',
        name: '本溪市',
        children: null,
      },
      {
        id: 136,
        parent_id: '2100',
        region_code: '2106',
        name: '丹东市',
        children: null,
      },
      {
        id: 135,
        parent_id: '2100',
        region_code: '2107',
        name: '锦州市',
        children: null,
      },
      {
        id: 139,
        parent_id: '2100',
        region_code: '2108',
        name: '营口市',
        children: null,
      },
      {
        id: 137,
        parent_id: '2100',
        region_code: '2109',
        name: '阜新市',
        children: null,
      },
      {
        id: 144,
        parent_id: '2100',
        region_code: '2110',
        name: '辽阳市',
        children: null,
      },
      {
        id: 143,
        parent_id: '2100',
        region_code: '2111',
        name: '盘锦市',
        children: null,
      },
      {
        id: 142,
        parent_id: '2100',
        region_code: '2112',
        name: '铁岭市',
        children: null,
      },
      {
        id: 140,
        parent_id: '2100',
        region_code: '2113',
        name: '朝阳市',
        children: null,
      },
      {
        id: 138,
        parent_id: '2100',
        region_code: '2114',
        name: '葫芦岛市',
        children: null,
      },
    ],
  },
  {
    id: 2200,
    parent_id: null,
    region_code: '2200',
    name: '吉林省',
    children: [
      {
        id: 286,
        parent_id: '2200',
        region_code: '2201',
        name: '长春市',
        children: null,
      },
      {
        id: 287,
        parent_id: '2200',
        region_code: '2202',
        name: '吉林市',
        children: null,
      },
      {
        id: 289,
        parent_id: '2200',
        region_code: '2203',
        name: '四平市',
        children: null,
      },
      {
        id: 294,
        parent_id: '2200',
        region_code: '2204',
        name: '辽源市',
        children: null,
      },
      {
        id: 291,
        parent_id: '2200',
        region_code: '2205',
        name: '通化市',
        children: null,
      },
      {
        id: 293,
        parent_id: '2200',
        region_code: '2206',
        name: '白山市',
        children: null,
      },
      {
        id: 290,
        parent_id: '2200',
        region_code: '2207',
        name: '松原市',
        children: null,
      },
      {
        id: 292,
        parent_id: '2200',
        region_code: '2208',
        name: '白城市',
        children: null,
      },
      {
        id: 288,
        parent_id: '2200',
        region_code: '2224',
        name: '延边朝鲜族自治州',
        children: null,
      },
    ],
  },
  {
    id: 2300,
    parent_id: null,
    region_code: '2300',
    name: '黑龙江省',
    children: [
      {
        id: 249,
        parent_id: '2300',
        region_code: '2301',
        name: '哈尔滨市',
        children: null,
      },
      {
        id: 251,
        parent_id: '2300',
        region_code: '2302',
        name: '齐齐哈尔市',
        children: null,
      },
      {
        id: 256,
        parent_id: '2300',
        region_code: '2303',
        name: '鸡西市',
        children: null,
      },
      {
        id: 259,
        parent_id: '2300',
        region_code: '2304',
        name: '鹤岗市',
        children: null,
      },
      {
        id: 258,
        parent_id: '2300',
        region_code: '2305',
        name: '双鸭山市',
        children: null,
      },
      {
        id: 250,
        parent_id: '2300',
        region_code: '2306',
        name: '大庆市',
        children: null,
      },
      {
        id: 255,
        parent_id: '2300',
        region_code: '2307',
        name: '伊春市',
        children: null,
      },
      {
        id: 254,
        parent_id: '2300',
        region_code: '2308',
        name: '佳木斯市',
        children: null,
      },
      {
        id: 260,
        parent_id: '2300',
        region_code: '2309',
        name: '七台河市',
        children: null,
      },
      {
        id: 252,
        parent_id: '2300',
        region_code: '2310',
        name: '牡丹江市',
        children: null,
      },
      {
        id: 257,
        parent_id: '2300',
        region_code: '2311',
        name: '黑河市',
        children: null,
      },
      {
        id: 253,
        parent_id: '2300',
        region_code: '2312',
        name: '绥化市',
        children: null,
      },
      {
        id: 261,
        parent_id: '2300',
        region_code: '2327',
        name: '大兴安岭地区',
        children: null,
      },
    ],
  },
  {
    id: 3100,
    parent_id: null,
    region_code: '3100',
    name: '上海市',
    children: null,
  },
  {
    id: 3200,
    parent_id: null,
    region_code: '3200',
    name: '江苏省',
    children: [
      {
        id: 84,
        parent_id: '3200',
        region_code: '3201',
        name: '南京市',
        children: null,
      },
      {
        id: 85,
        parent_id: '3200',
        region_code: '3202',
        name: '无锡市',
        children: null,
      },
      {
        id: 86,
        parent_id: '3200',
        region_code: '3203',
        name: '徐州市',
        children: null,
      },
      {
        id: 87,
        parent_id: '3200',
        region_code: '3204',
        name: '常州市',
        children: null,
      },
      {
        id: 83,
        parent_id: '3200',
        region_code: '3205',
        name: '苏州市',
        children: null,
      },
      {
        id: 88,
        parent_id: '3200',
        region_code: '3206',
        name: '南通市',
        children: null,
      },
      {
        id: 94,
        parent_id: '3200',
        region_code: '3207',
        name: '连云港市',
        children: null,
      },
      {
        id: 93,
        parent_id: '3200',
        region_code: '3208',
        name: '淮安市',
        children: null,
      },
      {
        id: 89,
        parent_id: '3200',
        region_code: '3209',
        name: '盐城市',
        children: null,
      },
      {
        id: 90,
        parent_id: '3200',
        region_code: '3210',
        name: '扬州市',
        children: null,
      },
      {
        id: 91,
        parent_id: '3200',
        region_code: '3211',
        name: '镇江市',
        children: null,
      },
      {
        id: 92,
        parent_id: '3200',
        region_code: '3212',
        name: '泰州市',
        children: null,
      },
      {
        id: 95,
        parent_id: '3200',
        region_code: '3213',
        name: '宿迁市',
        children: null,
      },
    ],
  },
  {
    id: 3300,
    parent_id: null,
    region_code: '3300',
    name: '浙江省',
    children: [
      {
        id: 71,
        parent_id: '3300',
        region_code: '3301',
        name: '杭州市',
        children: null,
      },
      {
        id: 72,
        parent_id: '3300',
        region_code: '3302',
        name: '宁波市',
        children: null,
      },
      {
        id: 73,
        parent_id: '3300',
        region_code: '3303',
        name: '温州市',
        children: null,
      },
      {
        id: 77,
        parent_id: '3300',
        region_code: '3304',
        name: '嘉兴市',
        children: null,
      },
      {
        id: 78,
        parent_id: '3300',
        region_code: '3305',
        name: '湖州市',
        children: null,
      },
      {
        id: 76,
        parent_id: '3300',
        region_code: '3306',
        name: '绍兴市',
        children: null,
      },
      {
        id: 75,
        parent_id: '3300',
        region_code: '3307',
        name: '金华市',
        children: null,
      },
      {
        id: 80,
        parent_id: '3300',
        region_code: '3308',
        name: '衢州市',
        children: null,
      },
      {
        id: 81,
        parent_id: '3300',
        region_code: '3309',
        name: '舟山市',
        children: null,
      },
      {
        id: 74,
        parent_id: '3300',
        region_code: '3310',
        name: '台州市',
        children: null,
      },
      {
        id: 79,
        parent_id: '3300',
        region_code: '3311',
        name: '丽水市',
        children: null,
      },
    ],
  },
  {
    id: 3400,
    parent_id: null,
    region_code: '3400',
    name: '安徽省',
    children: [
      {
        id: 232,
        parent_id: '3400',
        region_code: '3401',
        name: '合肥市',
        children: null,
      },
      {
        id: 236,
        parent_id: '3400',
        region_code: '3402',
        name: '芜湖市',
        children: null,
      },
      {
        id: 233,
        parent_id: '3400',
        region_code: '3403',
        name: '蚌埠市',
        children: null,
      },
      {
        id: 239,
        parent_id: '3400',
        region_code: '3404',
        name: '淮南市',
        children: null,
      },
      {
        id: 235,
        parent_id: '3400',
        region_code: '3405',
        name: '马鞍山市',
        children: null,
      },
      {
        id: 243,
        parent_id: '3400',
        region_code: '3406',
        name: '淮北市',
        children: null,
      },
      {
        id: 247,
        parent_id: '3400',
        region_code: '3407',
        name: '铜陵市',
        children: null,
      },
      {
        id: 237,
        parent_id: '3400',
        region_code: '3408',
        name: '安庆市',
        children: null,
      },
      {
        id: 244,
        parent_id: '3400',
        region_code: '3410',
        name: '黄山市',
        children: null,
      },
      {
        id: 240,
        parent_id: '3400',
        region_code: '3411',
        name: '滁州市',
        children: null,
      },
      {
        id: 238,
        parent_id: '3400',
        region_code: '3412',
        name: '阜阳市',
        children: null,
      },
      {
        id: 242,
        parent_id: '3400',
        region_code: '3413',
        name: '宿州市',
        children: null,
      },
      {
        id: 234,
        parent_id: '3400',
        region_code: '3415',
        name: '六安市',
        children: null,
      },
      {
        id: 245,
        parent_id: '3400',
        region_code: '3416',
        name: '亳州市',
        children: null,
      },
      {
        id: 246,
        parent_id: '3400',
        region_code: '3417',
        name: '池州市',
        children: null,
      },
      {
        id: 241,
        parent_id: '3400',
        region_code: '3418',
        name: '宣城市',
        children: null,
      },
    ],
  },
  {
    id: 3500,
    parent_id: null,
    region_code: '3500',
    name: '福建省',
    children: [
      {
        id: 210,
        parent_id: '3500',
        region_code: '3501',
        name: '福州市',
        children: null,
      },
      {
        id: 211,
        parent_id: '3500',
        region_code: '3502',
        name: '厦门市',
        children: null,
      },
      {
        id: 214,
        parent_id: '3500',
        region_code: '3503',
        name: '莆田市',
        children: null,
      },
      {
        id: 217,
        parent_id: '3500',
        region_code: '3504',
        name: '三明市',
        children: null,
      },
      {
        id: 212,
        parent_id: '3500',
        region_code: '3505',
        name: '泉州市',
        children: null,
      },
      {
        id: 213,
        parent_id: '3500',
        region_code: '3506',
        name: '漳州市',
        children: null,
      },
      {
        id: 218,
        parent_id: '3500',
        region_code: '3507',
        name: '南平市',
        children: null,
      },
      {
        id: 215,
        parent_id: '3500',
        region_code: '3508',
        name: '龙岩市',
        children: null,
      },
      {
        id: 216,
        parent_id: '3500',
        region_code: '3509',
        name: '宁德市',
        children: null,
      },
    ],
  },
  {
    id: 3600,
    parent_id: null,
    region_code: '3600',
    name: '江西省',
    children: [
      {
        id: 220,
        parent_id: '3600',
        region_code: '3601',
        name: '南昌市',
        children: null,
      },
      {
        id: 228,
        parent_id: '3600',
        region_code: '3602',
        name: '景德镇市',
        children: null,
      },
      {
        id: 227,
        parent_id: '3600',
        region_code: '3603',
        name: '萍乡市',
        children: null,
      },
      {
        id: 222,
        parent_id: '3600',
        region_code: '3604',
        name: '九江市',
        children: null,
      },
      {
        id: 229,
        parent_id: '3600',
        region_code: '3605',
        name: '新余市',
        children: null,
      },
      {
        id: 230,
        parent_id: '3600',
        region_code: '3606',
        name: '鹰潭市',
        children: null,
      },
      {
        id: 221,
        parent_id: '3600',
        region_code: '3607',
        name: '赣州市',
        children: null,
      },
      {
        id: 225,
        parent_id: '3600',
        region_code: '3608',
        name: '吉安市',
        children: null,
      },
      {
        id: 226,
        parent_id: '3600',
        region_code: '3609',
        name: '宜春市',
        children: null,
      },
      {
        id: 224,
        parent_id: '3600',
        region_code: '3610',
        name: '抚州市',
        children: null,
      },
      {
        id: 223,
        parent_id: '3600',
        region_code: '3611',
        name: '上饶市',
        children: null,
      },
    ],
  },
  {
    id: 3700,
    parent_id: null,
    region_code: '3700',
    name: '山东省',
    children: [
      {
        id: 98,
        parent_id: '3700',
        region_code: '3701',
        name: '济南市',
        children: null,
      },
      {
        id: 97,
        parent_id: '3700',
        region_code: '3702',
        name: '青岛市',
        children: null,
      },
      {
        id: 103,
        parent_id: '3700',
        region_code: '3703',
        name: '淄博市',
        children: null,
      },
      {
        id: 109,
        parent_id: '3700',
        region_code: '3704',
        name: '枣庄市',
        children: null,
      },
      {
        id: 111,
        parent_id: '3700',
        region_code: '3705',
        name: '东营市',
        children: null,
      },
      {
        id: 99,
        parent_id: '3700',
        region_code: '3706',
        name: '烟台市',
        children: null,
      },
      {
        id: 100,
        parent_id: '3700',
        region_code: '3707',
        name: '潍坊市',
        children: null,
      },
      {
        id: 102,
        parent_id: '3700',
        region_code: '3708',
        name: '济宁市',
        children: null,
      },
      {
        id: 105,
        parent_id: '3700',
        region_code: '3709',
        name: '泰安市',
        children: null,
      },
      {
        id: 106,
        parent_id: '3700',
        region_code: '3710',
        name: '威海市',
        children: null,
      },
      {
        id: 112,
        parent_id: '3700',
        region_code: '3711',
        name: '日照市',
        children: null,
      },
      {
        id: 101,
        parent_id: '3700',
        region_code: '3713',
        name: '临沂市',
        children: null,
      },
      {
        id: 107,
        parent_id: '3700',
        region_code: '3714',
        name: '德州市',
        children: null,
      },
      {
        id: 108,
        parent_id: '3700',
        region_code: '3715',
        name: '聊城市',
        children: null,
      },
      {
        id: 110,
        parent_id: '3700',
        region_code: '3716',
        name: '滨州市',
        children: null,
      },
      {
        id: 104,
        parent_id: '3700',
        region_code: '3717',
        name: '菏泽市',
        children: null,
      },
    ],
  },
  {
    id: 4100,
    parent_id: null,
    region_code: '4100',
    name: '河南省',
    children: [
      {
        id: 114,
        parent_id: '4100',
        region_code: '4101',
        name: '郑州市',
        children: null,
      },
      {
        id: 120,
        parent_id: '4100',
        region_code: '4102',
        name: '开封市',
        children: null,
      },
      {
        id: 115,
        parent_id: '4100',
        region_code: '4103',
        name: '洛阳市',
        children: null,
      },
      {
        id: 123,
        parent_id: '4100',
        region_code: '4104',
        name: '平顶山市',
        children: null,
      },
      {
        id: 118,
        parent_id: '4100',
        region_code: '4105',
        name: '安阳市',
        children: null,
      },
      {
        id: 130,
        parent_id: '4100',
        region_code: '4106',
        name: '鹤壁市',
        children: null,
      },
      {
        id: 116,
        parent_id: '4100',
        region_code: '4107',
        name: '新乡市',
        children: null,
      },
      {
        id: 122,
        parent_id: '4100',
        region_code: '4108',
        name: '焦作市',
        children: null,
      },
      {
        id: 124,
        parent_id: '4100',
        region_code: '4109',
        name: '濮阳市',
        children: null,
      },
      {
        id: 127,
        parent_id: '4100',
        region_code: '4110',
        name: '许昌市',
        children: null,
      },
      {
        id: 129,
        parent_id: '4100',
        region_code: '4111',
        name: '漯河市',
        children: null,
      },
      {
        id: 128,
        parent_id: '4100',
        region_code: '4112',
        name: '三门峡市',
        children: null,
      },
      {
        id: 117,
        parent_id: '4100',
        region_code: '4113',
        name: '南阳市',
        children: null,
      },
      {
        id: 119,
        parent_id: '4100',
        region_code: '4114',
        name: '商丘市',
        children: null,
      },
      {
        id: 125,
        parent_id: '4100',
        region_code: '4115',
        name: '信阳市',
        children: null,
      },
      {
        id: 126,
        parent_id: '4100',
        region_code: '4116',
        name: '周口市',
        children: null,
      },
      {
        id: 121,
        parent_id: '4100',
        region_code: '4117',
        name: '驻马店市',
        children: null,
      },
    ],
  },
  {
    id: 4200,
    parent_id: null,
    region_code: '4200',
    name: '湖北省',
    children: [
      {
        id: 181,
        parent_id: '4200',
        region_code: '4201',
        name: '武汉市',
        children: null,
      },
      {
        id: 187,
        parent_id: '4200',
        region_code: '4202',
        name: '黄石市',
        children: null,
      },
      {
        id: 188,
        parent_id: '4200',
        region_code: '4203',
        name: '十堰市',
        children: null,
      },
      {
        id: 183,
        parent_id: '4200',
        region_code: '4205',
        name: '宜昌市',
        children: null,
      },
      {
        id: 182,
        parent_id: '4200',
        region_code: '4206',
        name: '襄阳市',
        children: null,
      },
      {
        id: 193,
        parent_id: '4200',
        region_code: '4207',
        name: '鄂州市',
        children: null,
      },
      {
        id: 189,
        parent_id: '4200',
        region_code: '4208',
        name: '荆门市',
        children: null,
      },
      {
        id: 186,
        parent_id: '4200',
        region_code: '4209',
        name: '孝感市',
        children: null,
      },
      {
        id: 184,
        parent_id: '4200',
        region_code: '4210',
        name: '荆州市',
        children: null,
      },
      {
        id: 185,
        parent_id: '4200',
        region_code: '4211',
        name: '黄冈市',
        children: null,
      },
      {
        id: 190,
        parent_id: '4200',
        region_code: '4212',
        name: '咸宁市',
        children: null,
      },
      {
        id: 192,
        parent_id: '4200',
        region_code: '4213',
        name: '随州市',
        children: null,
      },
      {
        id: 191,
        parent_id: '4200',
        region_code: '4228',
        name: '恩施土家族苗族自治州',
        children: null,
      },
    ],
  },
  {
    id: 4300,
    parent_id: null,
    region_code: '4300',
    name: '湖南省',
    children: [
      {
        id: 195,
        parent_id: '4300',
        region_code: '4301',
        name: '长沙市',
        children: null,
      },
      {
        id: 205,
        parent_id: '4300',
        region_code: '4302',
        name: '株洲市',
        children: null,
      },
      {
        id: 198,
        parent_id: '4300',
        region_code: '4303',
        name: '湘潭市',
        children: null,
      },
      {
        id: 196,
        parent_id: '4300',
        region_code: '4304',
        name: '衡阳市',
        children: null,
      },
      {
        id: 200,
        parent_id: '4300',
        region_code: '4305',
        name: '邵阳市',
        children: null,
      },
      {
        id: 201,
        parent_id: '4300',
        region_code: '4306',
        name: '岳阳市',
        children: null,
      },
      {
        id: 206,
        parent_id: '4300',
        region_code: '4307',
        name: '常德市',
        children: null,
      },
      {
        id: 208,
        parent_id: '4300',
        region_code: '4308',
        name: '张家界市',
        children: null,
      },
      {
        id: 197,
        parent_id: '4300',
        region_code: '4309',
        name: '益阳市',
        children: null,
      },
      {
        id: 199,
        parent_id: '4300',
        region_code: '4310',
        name: '郴州市',
        children: null,
      },
      {
        id: 203,
        parent_id: '4300',
        region_code: '4311',
        name: '永州市',
        children: null,
      },
      {
        id: 204,
        parent_id: '4300',
        region_code: '4312',
        name: '怀化市',
        children: null,
      },
      {
        id: 202,
        parent_id: '4300',
        region_code: '4313',
        name: '娄底市',
        children: null,
      },
      {
        id: 207,
        parent_id: '4300',
        region_code: '4331',
        name: '湘西土家族苗族自治州',
        children: null,
      },
    ],
  },
  {
    id: 4400,
    parent_id: null,
    region_code: '4400',
    name: '广东省',
    children: [
      {
        id: 49,
        parent_id: '4400',
        region_code: '4401',
        name: '广州市',
        children: null,
      },
      {
        id: 62,
        parent_id: '4400',
        region_code: '4402',
        name: '韶关市',
        children: null,
      },
      {
        id: 50,
        parent_id: '4400',
        region_code: '4403',
        name: '深圳市',
        children: null,
      },
      {
        id: 56,
        parent_id: '4400',
        region_code: '4404',
        name: '珠海市',
        children: null,
      },
      {
        id: 55,
        parent_id: '4400',
        region_code: '4405',
        name: '汕头市',
        children: null,
      },
      {
        id: 52,
        parent_id: '4400',
        region_code: '4406',
        name: '佛山市',
        children: null,
      },
      {
        id: 57,
        parent_id: '4400',
        region_code: '4407',
        name: '江门市',
        children: null,
      },
      {
        id: 58,
        parent_id: '4400',
        region_code: '4408',
        name: '湛江市',
        children: null,
      },
      {
        id: 60,
        parent_id: '4400',
        region_code: '4409',
        name: '茂名市',
        children: null,
      },
      {
        id: 61,
        parent_id: '4400',
        region_code: '4412',
        name: '肇庆市',
        children: null,
      },
      {
        id: 53,
        parent_id: '4400',
        region_code: '4413',
        name: '惠州市',
        children: null,
      },
      {
        id: 63,
        parent_id: '4400',
        region_code: '4414',
        name: '梅州市',
        children: null,
      },
      {
        id: 66,
        parent_id: '4400',
        region_code: '4415',
        name: '汕尾市',
        children: null,
      },
      {
        id: 67,
        parent_id: '4400',
        region_code: '4416',
        name: '河源市',
        children: null,
      },
      {
        id: 68,
        parent_id: '4400',
        region_code: '4417',
        name: '阳江市',
        children: null,
      },
      {
        id: 64,
        parent_id: '4400',
        region_code: '4418',
        name: '清远市',
        children: null,
      },
      {
        id: 51,
        parent_id: '4400',
        region_code: '4419',
        name: '东莞市',
        children: null,
      },
      {
        id: 54,
        parent_id: '4400',
        region_code: '4420',
        name: '中山市',
        children: null,
      },
      {
        id: 65,
        parent_id: '4400',
        region_code: '4451',
        name: '潮州市',
        children: null,
      },
      {
        id: 59,
        parent_id: '4400',
        region_code: '4452',
        name: '揭阳市',
        children: null,
      },
      {
        id: 69,
        parent_id: '4400',
        region_code: '4453',
        name: '云浮市',
        children: null,
      },
    ],
  },
  {
    id: 4500,
    parent_id: null,
    region_code: '4500',
    name: '广西壮族自治区',
    children: [
      {
        id: 296,
        parent_id: '4500',
        region_code: '4501',
        name: '南宁市',
        children: null,
      },
      {
        id: 298,
        parent_id: '4500',
        region_code: '4502',
        name: '柳州市',
        children: null,
      },
      {
        id: 297,
        parent_id: '4500',
        region_code: '4503',
        name: '桂林市',
        children: null,
      },
      {
        id: 304,
        parent_id: '4500',
        region_code: '4504',
        name: '梧州市',
        children: null,
      },
      {
        id: 301,
        parent_id: '4500',
        region_code: '4505',
        name: '北海市',
        children: null,
      },
      {
        id: 309,
        parent_id: '4500',
        region_code: '4506',
        name: '防城港市',
        children: null,
      },
      {
        id: 300,
        parent_id: '4500',
        region_code: '4507',
        name: '钦州市',
        children: null,
      },
      {
        id: 305,
        parent_id: '4500',
        region_code: '4508',
        name: '贵港市',
        children: null,
      },
      {
        id: 299,
        parent_id: '4500',
        region_code: '4509',
        name: '玉林市',
        children: null,
      },
      {
        id: 302,
        parent_id: '4500',
        region_code: '4510',
        name: '百色市',
        children: null,
      },
      {
        id: 308,
        parent_id: '4500',
        region_code: '4511',
        name: '贺州市',
        children: null,
      },
      {
        id: 303,
        parent_id: '4500',
        region_code: '4512',
        name: '河池市',
        children: null,
      },
      {
        id: 307,
        parent_id: '4500',
        region_code: '4513',
        name: '来宾市',
        children: null,
      },
      {
        id: 306,
        parent_id: '4500',
        region_code: '4514',
        name: '崇左市',
        children: null,
      },
    ],
  },
  {
    id: 4600,
    parent_id: null,
    region_code: '4600',
    name: '海南省',
    children: [
      {
        id: 381,
        parent_id: '4600',
        region_code: '4601',
        name: '海口市',
        children: null,
      },
      {
        id: 382,
        parent_id: '4600',
        region_code: '4602',
        name: '三亚市',
        children: null,
      },
      {
        id: 384,
        parent_id: '4600',
        region_code: '4603',
        name: '三沙市',
        children: null,
      },
      {
        id: 383,
        parent_id: '4600',
        region_code: '4604',
        name: '儋州市',
        children: null,
      },
    ],
  },
  {
    id: 5000,
    parent_id: null,
    region_code: '5000',
    name: '重庆市',
    children: null,
  },
  {
    id: 5100,
    parent_id: null,
    region_code: '5100',
    name: '四川省',
    children: [
      {
        id: 147,
        parent_id: '5100',
        region_code: '5101',
        name: '成都市',
        children: null,
      },
      {
        id: 156,
        parent_id: '5100',
        region_code: '5103',
        name: '自贡市',
        children: null,
      },
      {
        id: 161,
        parent_id: '5100',
        region_code: '5104',
        name: '攀枝花市',
        children: null,
      },
      {
        id: 151,
        parent_id: '5100',
        region_code: '5105',
        name: '泸州市',
        children: null,
      },
      {
        id: 154,
        parent_id: '5100',
        region_code: '5106',
        name: '德阳市',
        children: null,
      },
      {
        id: 148,
        parent_id: '5100',
        region_code: '5107',
        name: '绵阳市',
        children: null,
      },
      {
        id: 160,
        parent_id: '5100',
        region_code: '5108',
        name: '广元市',
        children: null,
      },
      {
        id: 162,
        parent_id: '5100',
        region_code: '5109',
        name: '遂宁市',
        children: null,
      },
      {
        id: 157,
        parent_id: '5100',
        region_code: '5110',
        name: '内江市',
        children: null,
      },
      {
        id: 150,
        parent_id: '5100',
        region_code: '5111',
        name: '乐山市',
        children: null,
      },
      {
        id: 149,
        parent_id: '5100',
        region_code: '5113',
        name: '南充市',
        children: null,
      },
      {
        id: 155,
        parent_id: '5100',
        region_code: '5114',
        name: '眉山市',
        children: null,
      },
      {
        id: 152,
        parent_id: '5100',
        region_code: '5115',
        name: '宜宾市',
        children: null,
      },
      {
        id: 159,
        parent_id: '5100',
        region_code: '5116',
        name: '广安市',
        children: null,
      },
      {
        id: 153,
        parent_id: '5100',
        region_code: '5117',
        name: '达州市',
        children: null,
      },
      {
        id: 164,
        parent_id: '5100',
        region_code: '5118',
        name: '雅安市',
        children: null,
      },
      {
        id: 165,
        parent_id: '5100',
        region_code: '5119',
        name: '巴中市',
        children: null,
      },
      {
        id: 163,
        parent_id: '5100',
        region_code: '5120',
        name: '资阳市',
        children: null,
      },
      {
        id: 166,
        parent_id: '5100',
        region_code: '5132',
        name: '阿坝藏族羌族自治州',
        children: null,
      },
      {
        id: 167,
        parent_id: '5100',
        region_code: '5133',
        name: '甘孜藏族自治州',
        children: null,
      },
      {
        id: 158,
        parent_id: '5100',
        region_code: '5134',
        name: '凉山彝族自治州',
        children: null,
      },
    ],
  },
  {
    id: 5200,
    parent_id: null,
    region_code: '5200',
    name: '贵州省',
    children: [
      {
        id: 356,
        parent_id: '5200',
        region_code: '5201',
        name: '贵阳市',
        children: null,
      },
      {
        id: 361,
        parent_id: '5200',
        region_code: '5202',
        name: '六盘水市',
        children: null,
      },
      {
        id: 357,
        parent_id: '5200',
        region_code: '5203',
        name: '遵义市',
        children: null,
      },
      {
        id: 362,
        parent_id: '5200',
        region_code: '5204',
        name: '安顺市',
        children: null,
      },
      {
        id: 364,
        parent_id: '5200',
        region_code: '5205',
        name: '毕节市',
        children: null,
      },
      {
        id: 360,
        parent_id: '5200',
        region_code: '5206',
        name: '铜仁市',
        children: null,
      },
      {
        id: 359,
        parent_id: '5200',
        region_code: '5223',
        name: '黔西南布依族苗族自治州',
        children: null,
      },
      {
        id: 363,
        parent_id: '5200',
        region_code: '5226',
        name: '黔东南苗族侗族自治州',
        children: null,
      },
      {
        id: 358,
        parent_id: '5200',
        region_code: '5227',
        name: '黔南布依族苗族自治州',
        children: null,
      },
    ],
  },
  {
    id: 5300,
    parent_id: null,
    region_code: '5300',
    name: '云南省',
    children: [
      {
        id: 326,
        parent_id: '5300',
        region_code: '5301',
        name: '昆明市',
        children: null,
      },
      {
        id: 329,
        parent_id: '5300',
        region_code: '5303',
        name: '曲靖市',
        children: null,
      },
      {
        id: 330,
        parent_id: '5300',
        region_code: '5304',
        name: '玉溪市',
        children: null,
      },
      {
        id: 337,
        parent_id: '5300',
        region_code: '5305',
        name: '保山市',
        children: null,
      },
      {
        id: 332,
        parent_id: '5300',
        region_code: '5306',
        name: '昭通市',
        children: null,
      },
      {
        id: 335,
        parent_id: '5300',
        region_code: '5307',
        name: '丽江市',
        children: null,
      },
      {
        id: 333,
        parent_id: '5300',
        region_code: '5308',
        name: '普洱市',
        children: null,
      },
      {
        id: 339,
        parent_id: '5300',
        region_code: '5309',
        name: '临沧市',
        children: null,
      },
      {
        id: 331,
        parent_id: '5300',
        region_code: '5323',
        name: '楚雄彝族自治州',
        children: null,
      },
      {
        id: 327,
        parent_id: '5300',
        region_code: '5325',
        name: '红河哈尼族彝族自治州',
        children: null,
      },
      {
        id: 334,
        parent_id: '5300',
        region_code: '5326',
        name: '文山壮族苗族自治州',
        children: null,
      },
      {
        id: 336,
        parent_id: '5300',
        region_code: '5328',
        name: '西双版纳傣族自治州',
        children: null,
      },
      {
        id: 328,
        parent_id: '5300',
        region_code: '5329',
        name: '大理白族自治州',
        children: null,
      },
      {
        id: 338,
        parent_id: '5300',
        region_code: '5331',
        name: '德宏傣族景颇族自治州',
        children: null,
      },
      {
        id: 340,
        parent_id: '5300',
        region_code: '5333',
        name: '怒江傈僳族自治州',
        children: null,
      },
      {
        id: 341,
        parent_id: '5300',
        region_code: '5334',
        name: '迪庆藏族自治州',
        children: null,
      },
    ],
  },
  {
    id: 5400,
    parent_id: null,
    region_code: '5400',
    name: '西藏自治区',
    children: [
      {
        id: 401,
        parent_id: '5400',
        region_code: '5401',
        name: '拉萨市',
        children: null,
      },
      {
        id: 403,
        parent_id: '5400',
        region_code: '5402',
        name: '日喀则市',
        children: null,
      },
      {
        id: 402,
        parent_id: '5400',
        region_code: '5403',
        name: '昌都市',
        children: null,
      },
      {
        id: 405,
        parent_id: '5400',
        region_code: '5404',
        name: '林芝市',
        children: null,
      },
      {
        id: 404,
        parent_id: '5400',
        region_code: '5405',
        name: '山南市',
        children: null,
      },
      {
        id: 407,
        parent_id: '5400',
        region_code: '5406',
        name: '那曲市',
        children: null,
      },
      {
        id: 406,
        parent_id: '5400',
        region_code: '5425',
        name: '阿里地区',
        children: null,
      },
    ],
  },
  {
    id: 6100,
    parent_id: null,
    region_code: '6100',
    name: '陕西省',
    children: [
      {
        id: 275,
        parent_id: '6100',
        region_code: '6101',
        name: '西安市',
        children: null,
      },
      {
        id: 284,
        parent_id: '6100',
        region_code: '6102',
        name: '铜川市',
        children: null,
      },
      {
        id: 280,
        parent_id: '6100',
        region_code: '6103',
        name: '宝鸡市',
        children: null,
      },
      {
        id: 276,
        parent_id: '6100',
        region_code: '6104',
        name: '咸阳市',
        children: null,
      },
      {
        id: 279,
        parent_id: '6100',
        region_code: '6105',
        name: '渭南市',
        children: null,
      },
      {
        id: 277,
        parent_id: '6100',
        region_code: '6106',
        name: '延安市',
        children: null,
      },
      {
        id: 282,
        parent_id: '6100',
        region_code: '6107',
        name: '汉中市',
        children: null,
      },
      {
        id: 281,
        parent_id: '6100',
        region_code: '6108',
        name: '榆林市',
        children: null,
      },
      {
        id: 278,
        parent_id: '6100',
        region_code: '6109',
        name: '安康市',
        children: null,
      },
      {
        id: 283,
        parent_id: '6100',
        region_code: '6110',
        name: '商洛市',
        children: null,
      },
    ],
  },
  {
    id: 6200,
    parent_id: null,
    region_code: '6200',
    name: '甘肃省',
    children: [
      {
        id: 366,
        parent_id: '6200',
        region_code: '6201',
        name: '兰州市',
        children: null,
      },
      {
        id: 379,
        parent_id: '6200',
        region_code: '6202',
        name: '嘉峪关市',
        children: null,
      },
      {
        id: 374,
        parent_id: '6200',
        region_code: '6203',
        name: '金昌市',
        children: null,
      },
      {
        id: 373,
        parent_id: '6200',
        region_code: '6204',
        name: '白银市',
        children: null,
      },
      {
        id: 369,
        parent_id: '6200',
        region_code: '6205',
        name: '天水市',
        children: null,
      },
      {
        id: 370,
        parent_id: '6200',
        region_code: '6206',
        name: '武威市',
        children: null,
      },
      {
        id: 367,
        parent_id: '6200',
        region_code: '6207',
        name: '张掖市',
        children: null,
      },
      {
        id: 372,
        parent_id: '6200',
        region_code: '6208',
        name: '平凉市',
        children: null,
      },
      {
        id: 368,
        parent_id: '6200',
        region_code: '6209',
        name: '酒泉市',
        children: null,
      },
      {
        id: 371,
        parent_id: '6200',
        region_code: '6210',
        name: '庆阳市',
        children: null,
      },
      {
        id: 377,
        parent_id: '6200',
        region_code: '6211',
        name: '定西市',
        children: null,
      },
      {
        id: 375,
        parent_id: '6200',
        region_code: '6212',
        name: '陇南市',
        children: null,
      },
      {
        id: 376,
        parent_id: '6200',
        region_code: '6229',
        name: '临夏回族自治州',
        children: null,
      },
      {
        id: 378,
        parent_id: '6200',
        region_code: '6230',
        name: '甘南藏族自治州',
        children: null,
      },
    ],
  },
  {
    id: 6300,
    parent_id: null,
    region_code: '6300',
    name: '青海省',
    children: [
      {
        id: 392,
        parent_id: '6300',
        region_code: '6301',
        name: '西宁市',
        children: null,
      },
      {
        id: 393,
        parent_id: '6300',
        region_code: '6302',
        name: '海东市',
        children: null,
      },
      {
        id: 396,
        parent_id: '6300',
        region_code: '6322',
        name: '海北藏族自治州',
        children: null,
      },
      {
        id: 398,
        parent_id: '6300',
        region_code: '6323',
        name: '黄南藏族自治州',
        children: null,
      },
      {
        id: 395,
        parent_id: '6300',
        region_code: '6325',
        name: '海南藏族自治州',
        children: null,
      },
      {
        id: 399,
        parent_id: '6300',
        region_code: '6326',
        name: '果洛藏族自治州',
        children: null,
      },
      {
        id: 397,
        parent_id: '6300',
        region_code: '6327',
        name: '玉树藏族自治州',
        children: null,
      },
      {
        id: 394,
        parent_id: '6300',
        region_code: '6328',
        name: '海西蒙古族藏族自治州',
        children: null,
      },
    ],
  },
  {
    id: 6400,
    parent_id: null,
    region_code: '6400',
    name: '宁夏回族自治区',
    children: [
      {
        id: 386,
        parent_id: '6400',
        region_code: '6401',
        name: '银川市',
        children: null,
      },
      {
        id: 389,
        parent_id: '6400',
        region_code: '6402',
        name: '石嘴山市',
        children: null,
      },
      {
        id: 390,
        parent_id: '6400',
        region_code: '6403',
        name: '吴忠市',
        children: null,
      },
      {
        id: 388,
        parent_id: '6400',
        region_code: '6404',
        name: '固原市',
        children: null,
      },
      {
        id: 387,
        parent_id: '6400',
        region_code: '6405',
        name: '中卫市',
        children: null,
      },
    ],
  },
  {
    id: 6500,
    parent_id: null,
    region_code: '6500',
    name: '新疆维吾尔自治区',
    children: [
      {
        id: 311,
        parent_id: '6500',
        region_code: '6501',
        name: '乌鲁木齐市',
        children: null,
      },
      {
        id: 322,
        parent_id: '6500',
        region_code: '6502',
        name: '克拉玛依市',
        children: null,
      },
      {
        id: 324,
        parent_id: '6500',
        region_code: '6504',
        name: '吐鲁番市',
        children: null,
      },
      {
        id: 319,
        parent_id: '6500',
        region_code: '6505',
        name: '哈密市',
        children: null,
      },
      {
        id: 320,
        parent_id: '6500',
        region_code: '6523',
        name: '昌吉回族自治州',
        children: null,
      },
      {
        id: 321,
        parent_id: '6500',
        region_code: '6527',
        name: '博尔塔拉蒙古自治州',
        children: null,
      },
      {
        id: 316,
        parent_id: '6500',
        region_code: '6528',
        name: '巴音郭楞蒙古自治州',
        children: null,
      },
      {
        id: 314,
        parent_id: '6500',
        region_code: '6529',
        name: '阿克苏地区',
        children: null,
      },
      {
        id: 323,
        parent_id: '6500',
        region_code: '6530',
        name: '克孜勒苏柯尔克孜自治州',
        children: null,
      },
      {
        id: 318,
        parent_id: '6500',
        region_code: '6531',
        name: '喀什地区',
        children: null,
      },
      {
        id: 315,
        parent_id: '6500',
        region_code: '6532',
        name: '和田地区',
        children: null,
      },
      {
        id: 313,
        parent_id: '6500',
        region_code: '6540',
        name: '伊犁哈萨克自治州',
        children: null,
      },
      {
        id: 312,
        parent_id: '6500',
        region_code: '6542',
        name: '塔城地区',
        children: null,
      },
      {
        id: 317,
        parent_id: '6500',
        region_code: '6543',
        name: '阿勒泰地区',
        children: null,
      },
    ],
  },
  {
    id: 7100,
    parent_id: null,
    region_code: '7100',
    name: '台湾省',
    children: [
      {
        id: 411,
        parent_id: '7100',
        region_code: '7101',
        name: '新北市',
        children: null,
      },
      {
        id: 412,
        parent_id: '7100',
        region_code: '7102',
        name: '高雄市',
        children: null,
      },
      {
        id: 410,
        parent_id: '7100',
        region_code: '7103',
        name: '台中市',
        children: null,
      },
      {
        id: 409,
        parent_id: '7100',
        region_code: '7104',
        name: '台北市',
        children: null,
      },
      {
        id: 413,
        parent_id: '7100',
        region_code: '7105',
        name: '桃园市',
        children: null,
      },
      {
        id: 414,
        parent_id: '7100',
        region_code: '7106',
        name: '台南市',
        children: null,
      },
      {
        id: 415,
        parent_id: '7100',
        region_code: '7107',
        name: '彰化县',
        children: null,
      },
      {
        id: 418,
        parent_id: '7100',
        region_code: '7108',
        name: '屏东县',
        children: null,
      },
      {
        id: 417,
        parent_id: '7100',
        region_code: '7109',
        name: '云林县',
        children: null,
      },
      {
        id: 421,
        parent_id: '7100',
        region_code: '7110',
        name: '苗栗县',
        children: null,
      },
      {
        id: 424,
        parent_id: '7100',
        region_code: '7111',
        name: '新竹县',
        children: null,
      },
      {
        id: 425,
        parent_id: '7100',
        region_code: '7112',
        name: '嘉义县',
        children: null,
      },
      {
        id: 422,
        parent_id: '7100',
        region_code: '7113',
        name: '南投县',
        children: null,
      },
      {
        id: 420,
        parent_id: '7100',
        region_code: '7114',
        name: '宜兰县',
        children: null,
      },
      {
        id: 416,
        parent_id: '7100',
        region_code: '7115',
        name: '新竹市',
        children: null,
      },
      {
        id: 427,
        parent_id: '7100',
        region_code: '7116',
        name: '基隆市',
        children: null,
      },
      {
        id: 423,
        parent_id: '7100',
        region_code: '7117',
        name: '花莲县',
        children: null,
      },
      {
        id: 419,
        parent_id: '7100',
        region_code: '7118',
        name: '嘉义市',
        children: null,
      },
      {
        id: 426,
        parent_id: '7100',
        region_code: '7119',
        name: '台东县',
        children: null,
      },
      {
        id: 428,
        parent_id: '7100',
        region_code: '7120',
        name: '金门县',
        children: null,
      },
      {
        id: 429,
        parent_id: '7100',
        region_code: '7121',
        name: '澎湖县',
        children: null,
      },
      {
        id: 430,
        parent_id: '7100',
        region_code: '7122',
        name: '连江县',
        children: null,
      },
    ],
  },
];
